# Generated by Django 4.1.7 on 2023-05-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminpanel', '0002_remove_spares_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spares',
            name='status',
            field=models.CharField(choices=[('b/y', 'b/y'), ('new', 'new')], default='new', max_length=255),
        ),
    ]
